"""create post_templates

Revision ID: 788263d7ad5c
Revises: b0a455c67213
Create Date: 2026-01-15 08:32:36.791590

"""
from alembic import op
import sqlalchemy as sa

revision = '788263d7ad5c'
down_revision = 'b0a455c67213'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Enum('voice', 'photo', 'video', 'document', 'video_note', name='media_type'), nullable=True),
    sa.Column('file_id', sa.String(length=512), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_templates_key'), 'post_templates', ['key'], unique=True)
    op.drop_index('ix_posts_code', table_name='posts')
    op.drop_table('posts')
    op.add_column('settings', sa.Column('key', sa.String(length=64), nullable=False))
    op.add_column('settings', sa.Column('value', sa.String(length=512), nullable=False))
    op.drop_column('settings', 'max_reminders')
    op.drop_column('settings', 'subscribe_channel')
    op.drop_column('settings', 'register_url')
    op.drop_column('settings', 'consult_url')
    op.drop_column('settings', 'inactive_hours')
    op.drop_column('settings', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('settings', sa.Column('inactive_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('settings', sa.Column('consult_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('settings', sa.Column('register_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.add_column('settings', sa.Column('subscribe_channel', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('settings', sa.Column('max_reminders', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('settings', 'value')
    op.drop_column('settings', 'key')
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('media_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('media_file_id', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('link_text', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('link_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    op.create_index('ix_posts_code', 'posts', ['code'], unique=True)
    op.drop_index(op.f('ix_post_templates_key'), table_name='post_templates')
    op.drop_table('post_templates')
    # ### end Alembic commands ###
