"""init

Revision ID: b0a455c67213
Revises: 
Create Date: 2026-01-14 22:03:54.326031

"""
from alembic import op
import sqlalchemy as sa

revision = 'b0a455c67213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('media_file_id', sa.String(length=512), nullable=True),
    sa.Column('link_text', sa.String(length=64), nullable=True),
    sa.Column('link_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_code'), 'posts', ['code'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscribe_channel', sa.String(length=255), nullable=False),
    sa.Column('register_url', sa.String(length=1024), nullable=False),
    sa.Column('consult_url', sa.String(length=1024), nullable=False),
    sa.Column('inactive_hours', sa.Integer(), nullable=False),
    sa.Column('max_reminders', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('is_subscribed', sa.Boolean(), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('reminder_step', sa.Integer(), nullable=False),
    sa.Column('last_reminder_at', sa.DateTime(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tg_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_index(op.f('ix_posts_code'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
